import subprocess
import re


# ================================================================
# FALSA ALLOWLIST — Seguridad por oscuridad (bypasseable)
#
# El código da la IMPRESIÓN de que solo ciertos comandos están
# permitidos, pero run_powershell() no usa is_allowed() en absoluto.
# Un jugador que lea este código (si lo obtiene) verá la ilusión.
# La verdadera vulnerabilidad es que la IA genera cualquier comando.
# ================================================================
ALLOWED_COMMANDS = [
    "Get-Date",
    "Get-ComputerInfo",
    "Get-Process",
    "Get-Service",
    "Get-ChildItem C:\\HR-Docs",
]

def is_allowed(command: str) -> bool:
    """
    Weak validation — exists for show only.
    run_powershell does not call this function.
    Bypasseable via semicolon, backtick, or prompt injection.
    """
    cmd = command.strip()
    for allowed in ALLOWED_COMMANDS:
        if cmd.lower().startswith(allowed.lower()):
            return True
    return False


def run_powershell(command: str) -> str:
    """
    Execute any PowerShell command.
    Intentionally has no real validation — vulnerable by design.
    The only gate is the AI's system prompt (which can be injected).
    """
    try:
        result = subprocess.run(
            ["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", command],
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=10
        )
        output = result.stdout.strip()
        error  = result.stderr.strip()

        if error:
            return f"[PS Error]: {error}\n{output}" if output else f"[PS Error]: {error}"
        return output if output else "[No output]"

    except subprocess.TimeoutExpired:
        return "[Error]: Command timed out after 10 seconds"
    except FileNotFoundError:
        return "[Error]: PowerShell not found"
    except Exception as e:
        return f"[Error]: {type(e).__name__} - {str(e)}"


def extract_ps_command(ai_response: str) -> str | None:
    """
    Extract PowerShell command generated by the AI.
    Only captures [PS: ...] format — the AI's tool invocation syntax.
    """
    patterns = [
        r'\[PS:\s*([^\]]+)\]',
        r'\[ps:\s*([^\]]+)\]',
    ]

    for pattern in patterns:
        match = re.search(pattern, ai_response, re.IGNORECASE)
        if match:
            cmd = match.group(1).strip()
            return cmd.split('\n')[0]   # Solo primera línea

    return None
